{% set name = "pyet" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyet-{{ version }}.tar.gz
  sha256: 0386fea15ae382d506b2178dc4755661bd06a23e72c84b6b9edae8f5f12d9581

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - xarray >=0.18.0
    - pandas >=1.0

test:
  imports:
    - pyet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/phydrus/pyet
  summary: pyet - Estimation of Potential Evaporation
  dev_url: https://github.com/phydrus/pyet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aslowwriter